-- MySQL Script generated by MySQL Workbench
-- Wed Aug  1 20:29:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pomodoro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pomodoro` ;

-- -----------------------------------------------------
-- Schema pomodoro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pomodoro` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `pomodoro` ;

-- -----------------------------------------------------
-- Table `Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Company` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `Company` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `id` ON `Company` () VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `RelationShip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationShip` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `RelationShip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid1` INT NOT NULL,
  `uid2` INT NOT NULL,
  `relation` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `Role` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `Role` (`name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(128) NOT NULL,
  `rid` INT NULL,
  `email` VARCHAR(64) NULL,
  `mobile` VARCHAR(32) NULL,
  `phone` VARCHAR(32) NULL,
  `first_name` VARCHAR(64) NULL,
  `last_name` VARCHAR(32) NULL,
  `sex` INT NULL,
  `country` VARCHAR(128) NULL,
  `address` VARCHAR(128) NULL,
  `wechat` VARCHAR(64) NULL,
  `qq` VARCHAR(64) NULL,
  `weibo` VARCHAR(64) NULL,
  `avator` VARCHAR(128) NULL,
  `create_time` DATETIME NULL,
  `create_ip` VARCHAR(128) NULL,
  `cid` INT NULL,
  `post` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `username_UNIQUE` ON `User` (`username` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UserAuth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserAuth` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `UserAuth` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NULL,
  `identity_type` VARCHAR(32) NULL,
  `identifier` VARCHAR(128) NULL,
  `credential` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `UserAuth` (`id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
